const products = [
  {
  _id: 1,
  name: 'Airpods',
  image: 'images/airpods.jpg',
  description: 'Cute as shit',
  brand: 'Apple',
  category: 'Electronics',
  price:89.99,
  countInStock:10,
  rating:4.9,
  numReviews:135,
},
{
  _id: 2,
  name: 'Alexa',
  image: 'images/alexa.jpg',
  description: 'Cute as shit',
  brand: 'Apple',
  category: 'Electronics',
  price:89.99,
  countInStock:10,
  rating:4.9,
  numReviews:135,
},

{
  _id: 3,
  name: 'Camera',
  image: 'images/camera.jpg',
  description: 'Cute as shit',
  brand: 'Apple',
  category: 'Electronics',
  price:89.99,
  countInStock:10,
  rating: 1,
  numReviews:135,
},

{
  _id: 4,
  name: 'Camera',
  image: 'images/camera.jpg',
  description: 'Cute as shit',
  brand: 'Apple',
  category: 'Electronics',
  price:89.99,
  countInStock:10,
  rating:0.5,
  numReviews:135,
},
{
  _id: 5,
  name: 'Camera',
  image: 'images/camera.jpg',
  description: 'Cute as shit',
  brand: 'Apple',
  category: 'Electronics',
  price:89.99,
  countInStock:10,
  rating: 2,
  numReviews:135,
},
{
  _id: 6,
  name: 'Camera',
  image: 'images/camera.jpg',
  description: 'Cute as shit',
  brand: 'Apple',
  category: 'Electronics',
  price:89.99,
  countInStock:10,
  rating:4,
  numReviews:135,
}
]


export default products